### ISSUE TITLE
Derive `Clone` for all public structs

### ISSUE THREAD

**Issue by omid** [kilork/keycloak#105]
It's better that public api structs derive `Clone`. (For example, `KeycloakAdminToken` doesn't have `Clone`)

And if possible/needed/makes-sense, also `Copy`, `Default`, `PartialEq`, `Eq`, `PartialOrd`, `Ord`, `Hash` and `Display`.

**Comment by omid** [comment]
Could you please release it @kilork?
I'm fine if it's in 24.0.300 also. ❤️

**Comment by kilork** [comment]
Should be safe to release as 24.0.300 I think, as we only add new derives. Will see
