### ISSUE TITLE
Endpoints with `Vec` input doesn't work!

### ISSUE THREAD

**Issue by omid** [kilork/keycloak#114]
Reqwest [doesn't support](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e37d474ce30c198d827ead2f533b3d1b) `Vec` as input of `query` method.

We have `Vec<String>` in two api calls. [Here](https://github.com/kilork/keycloak/blob/master/src/rest/generated_rest.rs#L5364) and [here](https://github.com/kilork/keycloak/blob/master/src/rest/generated_rest.rs#L5919).

We should either merge them with "," ourselves or just accept `String` instead.

**Comment by kilork** [comment]
The query parameters are actually multiplied in queries. If we have p parameter with value ['v1', 'v2'] in the end it will be p=v1&p=v2, not p=v1,v2. But seems like this really not supported by framework. Thought we can easy fix it. Thanks for reporting!

**Comment by omid** [comment]
Yes, you are right!
Funny that the Keycloak UI (the version I use) sends `type=LOGIN,LOGOUT` also, but then its backend returns 500 :D
But with curl `type=LOGIN&type=LOGOUT` works

**Comment by omid** [comment]
@kilork fixed
