### ISSUE TITLE
Keycloak server deserialization errors: `ClientPolicyExecutorConfigurationRepresentation` and `ClientPolicyConditionConfigurationRepresentation`

### ISSUE THREAD

**Issue by SimonThormeyer** [kilork/keycloak#130]
We at wire are using this crate to test our oidc flow with keycloak running in dev mode in a docker container. Thanks a lot!

However, we're currently running into issues when updating both the docker container and this crate to version 25.0.2.

When calling  `realm_client_policies_profiles_put()` with a `ClientPolicyExecutorRepresentation` in the body and `realm_client_policies_policies_put()` with a `ClientPolicyConditionRepresentation` in the body, the server responds with a 500 caused by a deserialization error.

When we change the `configuration`s in
https://github.com/kilork/keycloak/blob/19ce7cac0a0c26b2a9b17f92c46c2a24d8b4d4d1/src/types.rs#L380-L383
and
https://github.com/kilork/keycloak/blob/19ce7cac0a0c26b2a9b17f92c46c2a24d8b4d4d1/src/types.rs#L372-L375

to be an `Option<TypeMap<String, TypeValue>>` instead, our tests appear to be fixed.

Please note, if it's relevant, that the classes in the keycloak repository (see [here](https://github.com/keycloak/keycloak/blob/e750b44e9dec7e88db4f6cf1fd699a913d97a0ff/core/src/main/java/org/keycloak/representations/idm/ClientPolicyExecutorConfigurationRepresentation.java) and [here](https://github.com/keycloak/keycloak/blob/e750b44e9dec7e88db4f6cf1fd699a913d97a0ff/core/src/main/java/org/keycloak/representations/idm/ClientPolicyConditionConfigurationRepresentation.java)) use a map internally. 

What's the issue here?

**Comment by kilork** [comment]
Hi @SimonThormeyer Thank you for the report. I am not sure how exactly handle this, as the problem related to type description provided by `keycloak`. Basically it is in the `OpenAPI` description provided. You fix would not be permanent, as these structures are generated.

I previously had quite advanced way to patch types in HTML representation they used to have, could be we need here similar thing. Or we could report this to upstream and hope for better.

**Comment by SimonThormeyer** [comment]
Hi @kilork,
Thanks for your response. I see that there must be a problem with upstream's automated openAPI json generation. 
I would love to see it fixed there or provide them with a fix, I'm just not sure how the automated generation works, and thus I'm having trouble locating the bug.

**Comment by SimonThormeyer** [comment]
Reported at upstream in keycloak/keycloak#32004.

**Comment by kilork** [comment]
@SimonThormeyer to test changes you can use `update.ts`. It allows to run generator and some other nice things. I do releases with its help. About temporal fix need to think, how to do it better.

**Comment by istankovic** [comment]
> @SimonThormeyer to test changes you can use `update.ts`. It allows to run generator and some other nice things. I do releases with its help. About temporal fix need to think, how to do it better.

@kilork Any update on this?

**Comment by kilork** [comment]
@istankovic no, no update from my side, and upstream bug is also open. I actually do not think it is such a big deal to have proper swagger there.

On our side I need some almost zero-cost maintenance solution, releases here are pretty regular.
