### ISSUE TITLE
Resource and Permission APIs are not generated

### ISSUE THREAD

**Issue by kagetsuki1997** [kilork/keycloak#132]
APIs start with `/admin/realms/{realm}/clients/{client-uuid}/authz/*` are not generated.
I think it's cause by the `openapi.json` doesn't have tags of these apis.

**Comment by kilork** [comment]
@kagetsuki1997 you are absolutely right about the cause. I think previously they were not in the documentation as well, or I had not seen them, but now they are under `default` section, means we can interpret missing tag as `default` and fix it.
