### ISSUE TITLE
Support for Keycloak 15

### ISSUE THREAD

**Issue by malagant** [kilork/keycloak#18]
Hi @kilork,

i really like your approach to keycloak API. I currently use keycloak 15.1.1 and am wondering how compatible this crate is for 15. Is it possible to have this crate supporting keycloak 15 and up?
How is your approach to new versions? Through generating from API Specs?
I would love to support this project.

Cheers
Michael

**Comment by kilork** [comment]
Hi @malagant 

I am glad you like it! We are generating this crate from API docs. It would be really cool, if you make a contribution, sadly I have little time for my hobbies.

Update is not that complex, there is a script to do so. The only problem, is that this keycloak documentation is far from perfect, from some version they started to produce "stream" types, those do not have any type information. I have a config to do this mapping from unknown stream type to some type, which I guess would be returned back. If there were something like Swagger! Maybe there is some progress on that or better way, this is also a good question.

Also I wanted to change a lot in how we generate it. I mean API. Currently we have many optional parameters and it is a little bit unreadable in my opinion, when I need to pass ten `None`. It is just error prone, I would say. We definitely can do better!
