### ISSUE TITLE
Acquire KeycloakAdminToken via service account

### ISSUE THREAD

**Issue by criminosis** [kilork/keycloak#28]
It seems the library is lacking getting an admin token via a [service account](https://www.keycloak.org/docs/latest/server_development/#authenticate-with-a-service-account).

In my local checkout I've demonstrated that this works:

```
    pub async fn acquire_service(
        url: &str,
        client_id: &str,
        client_secret: &str,
        client: &reqwest::Client,
    ) -> Result<KeycloakAdminToken, KeycloakError> {
        let response = client
            .post(&format!(
                "{}/auth/realms/master/protocol/openid-connect/token",
                url,
            ))
            .form(&json!({
                "client_id": client_id,
                "client_secret": client_secret,
                "grant_type": "client_credentials"
            }))
            .send()
            .await?;
        Ok(error_check(response).await?.json().await?)
    }
```

I'd be happy to open up a PR to contribute it back up this weekend, just wondering if you'd have any pre-emptive suggestions or requests so I can make the PR as ready as possible out the gate.

From what I can tell the docs seemed to be wrong in the requirement of these:
> - client_id has a custom "Audience" mapper
> - Included Client Audience: security-admin-console

But I would mention the other requirements in the Doc comments

**Comment by kilork** [comment]
Hi, thank you for interest to this project.

I decided to not add extra functions to get authorisation token and instead just give the possibility to implement own token provider to user.

I lack knowledge about real use cases of `keycloak` admin API, so do not know, who is using admin account and who is using other ways to get authorisation token.

Your PR can be organised exactly in this form - add another implementation for `KeycloakTokenSupplier`.

**Comment by criminosis** [comment]
Makes sense. I'll get that out later today for your review. Thanks for the heads up about `KeycloakTokenSuppplier` 👍
