### ISSUE TITLE
jwt token has snake_case, but AccessToken serialization is camelCase

### ISSUE THREAD

**Issue by RossRogers** [kilork/keycloak#44]
Thanks for this fantastic library!

If I boot up a new keycloak 19 docker container and get a JWT token using `keycloak-js`, I get a JWT token like:
``` eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJQZnQ3Q1VaZWdJd0tseFh6VEp1ZFE3NDFHaVJRWlF4Vm0yUERvd0NRMm80In0.eyJleHAiOjE2NjQ3NTM5MTQsImlhdCI6MTY2NDc1MzYxNCwiYXV0aF90aW1lIjoxNjY0NzUzNjEyLCJqdGkiOiIzNjgyNjM0MS0zZmQwLTQ2MWYtOTFhYy00OTE5MWM1MTNhOGIiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL3VzZXJzIiwic3ViIjoiZWMyMTBlOWEtODUyNi00NDc0LTlhMjEtY2IzMGUwMzE0ODUxIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZnJvbnRlbmQiLCJub25jZSI6IjJiNmU2ZmEzLTM4MWUtNDI2Mi05ZmNjLTBhMTQ5NDdkNmJiYyIsInNlc3Npb25fc3RhdGUiOiI2MTdjYTYyNy05ZmYxLTQ4YTEtOWEwOC00YTkxZTJmZTYyMDQiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXVzZXJzIl19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwic2lkIjoiNjE3Y2E2MjctOWZmMS00OGExLTlhMDgtNGE5MWUyZmU2MjA0IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiRm9vIEJhciIsInByZWZlcnJlZF91c2VybmFtZSI6ImZvb0BleGFtcGxlLmNvbSIsImdpdmVuX25hbWUiOiJGb28iLCJmYW1pbHlfbmFtZSI6IkJhciIsImVtYWlsIjoiZm9vQGV4YW1wbGUuY29tIn0.OIGkZ8n0SeY1_zBRN5OgMzl_X49CJCj3fe7QR5A4o0u5PnI-gs3yPHnBASGR1irXsjLkGFrAxyg5AjQqvSduOdm1mGYsbtCQmlomINKkvL5AYKg_5bdy4YpHYJzp2DFtS3eXahHyDP5zfDfCs2ZrtNV4EDyIjurj_UR13sYwYOlD0DGC71WIS8ybj7YqXAiMozs0Gdia4TjwGEiQxuqv3k2ekAznl6xJ29yra--DlhpEPqdYx7PY44pCJYwjagEBlZlMnEtk2VGPTNWbw9JxdlzK9xkIV5oGeFgbBdOPv7Lj1BNbRgBHQMtF2l2ULrj2e4th0GEaO3i8pwLE1SM4CQ```

jwt.io deserializes this as:
```json
{
  "exp": 1664753914,
  "iat": 1664753614,
  "auth_time": 1664753612,
  "jti": "36826341-3fd0-461f-91ac-49191c513a8b",
  "iss": "http://localhost:8080/realms/users",
  "sub": "ec210e9a-8526-4474-9a21-cb30e0314851",
  "typ": "Bearer",
  "azp": "frontend",
  "nonce": "2b6e6fa3-381e-4262-9fcc-0a14947d6bbc",
  "session_state": "617ca627-9ff1-48a1-9a08-4a91e2fe6204",
  "acr": "1",
  "allowed-origins": [
    "*"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization",
      "default-roles-users"
    ]
  },
  "scope": "openid profile email",
  "sid": "617ca627-9ff1-48a1-9a08-4a91e2fe6204",
  "email_verified": false,
  "name": "Foo Bar",
  "preferred_username": "foo@example.com",
  "given_name": "Foo",
  "family_name": "Bar",
  "email": "foo@example.com"
}
```

When I deserialize this into rust, the `given_name` and `family_name` don't get deserialized.  Digging in to this, I see the following

```rust
#[skip_serializing_none]
#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")] // <---------------------------------------------------------------
pub struct AccessToken {
```

---
So, keycloak is returning snake_case JWT tokens by default, whereas `AccessToken` expects camelCase.  

Is this issue known?  Are users of this library expected to modify all mappers in Keycloak to be camelCased?

**Comment by kilork** [comment]
Hi, thanks for report. I think it is a bug.

The reason for this bug is how this library organized. We generate our types from REST API html document (as it is only one good source of API description I found).

Most of cases are `camelCase`, but seems like Keycloak is not consistent, or maybe it is the only one place with `snake_case`. This must be checked. In `Rust` we should have `snake_case` in structures. We have to complicate a little bit procedure of struct generation to overcome this issue.
