### ISSUE TITLE
Missing Type Info for Generics

### ISSUE THREAD

**Issue by Xiphoseer** [kilork/keycloak#48]
The [Admin REST API docs](https://www.keycloak.org/docs-api/20.0.1/rest-api/index.html), which you use to generate these rust bindings seem to be completely missing any information on generics.

For example, there's [`ComponentRepresentation::config`](https://docs.rs/keycloak/20.0.100/keycloak/types/struct.ComponentRepresentation.html#structfield.config), which is supposed to represent [`org.keycloak.component.ComponentModel.config`](https://github.com/keycloak/keycloak/blob/13fcb9ca34357e85e8b0870c7483c69cc884a658/server-spi/src/main/java/org/keycloak/component/ComponentModel.java#L39), which is a `MultivaluedHashMap<String, String>` in the keycloak source, but is just a `MultivaluedHashMap` in <https://www.keycloak.org/docs-api/20.0.1/rest-api/index.html#_componentrepresentation>. Furthermore, the definition of [`MultivaluedHashMap`](https://www.keycloak.org/docs-api/15.0/rest-api/index.html#_multivaluedhashmap) is completely useless because it doesn't match the JSON serialization, which would be `HashMap<K, Vec<V>>`.

I see three possible approaches to solve this:
1. Generate a `type MultivaluedHashMap = HashMap<String, Vec<serde_json::Value>>;` instead of the current struct. This is enough to make the APIs pretty, but also the bare minimum.
2. Special case any instance of `MultivaluedHashMap ` (and possibly other, similar cases) and provide the type info manually, for example with another toml file.
3. Use a different data source, like the typescript bindings from [https://www.npmjs.com/package/@keycloak/keycloak-admin-client](@keycloak/keycloak-admin-client), which seem to be actively maintained by the keycloak project at <https://github.com/keycloak/keycloak-nodejs-admin-client/tree/main/src/defs>

**Comment by kilork** [comment]
Thanks for this research! Yes, the docs for keycloak are not only bad, it gets worse with each new version. I hope this is not happenning with the whole product.

Most feasible and easy is to implement 1. Variant 2 is also possible, depending on how much cases we have and how we can describe missing structures. In the last version I added way to patch individual parameters: https://github.com/kilork/keycloak/blob/master/examples/stream.toml#L1.  I found 3 cases with `MultivaluedHashMap` and I prefer actually to be as specific as possible. Variant 3 I think is kinda difficult, parsing and patching html is way easier than parsing typescript.

Maybe we have also option 4 - go upstream and fix their docs?

**Comment by Xiphoseer** [comment]
I actually looked at what upstream does and it seems to be a bit all over the place. The `docs-api` folder is left untouched when the website rebuilds and seems to come out of the actual keycloak build.

The pom.xml in one of those modules seems to indicate that they use some 6 year old javadoc extension doclet to produce a swagger json (ie. openapi) which they then turn into markdown and then asciidoc for some reason.

The intermediate swagger json would probably be easier to read for the same content as the docs html, but IIRC that doesn't support genrics either.

So any upstream solution would need to use some intermediary format that is expressive enough to forward at least map generics info from Java to Rust anyways, which would probably be equivalent to porting that doclet to <https://openjdk.org/groups/compiler/using-new-doclet.html> and OpenApi v3
