### ISSUE TITLE
Connect  API REST in another realm 

### ISSUE THREAD

**Issue by benjamingb** [kilork/keycloak#54]
How do I connect through a API REST in another realm that is not master?
I didn't find an example

these are my parameters:
url: http://localhost:6033/auth/
realm: mytest 
username:test
password:test123
grant_type:password
client_id: apirest
client_secret: pb5TeYNUesNahGcAt785J

**Comment by kilork** [comment]
I think you can take idea from this code:

https://github.com/kilork/keycloak/pull/10/files

There is a method called `acquire_custom_realm`.

Documentation:

- https://docs.rs/keycloak/20.0.101/keycloak/struct.KeycloakAdminToken.html#method.acquire_custom_realm

**Comment by ovisan** [comment]
Ok and where do i supply the `client_secret`? I see only the `client_id` in the `aquire_custom_realm` method
