### ISSUE TITLE
Add feature to choose rustls over native-tls for reqwest dependency

### ISSUE THREAD

**Issue by Tenshock** [kilork/keycloak#66]
Currently, using [keycloak](https://docs.rs/keycloak/21.0.102/keycloak/) crate makes us depend on [reqwest](https://docs.rs/reqwest/0.11.19/reqwest/) with dependencies on [native-tls](https://crates.io/crates/native-tls) depending itself on [openssl](https://docs.rs/openssl/0.10.56/openssl/) crate. Thus, we have a dependency on [openssl](https://docs.rs/openssl/0.10.56/openssl/#automatic) OS dependencies.

It would be nice to have the opportunity to choose between native-tls and rustls, already supported by reqwest through the feature `rustls-tls` (more doc here [Reqwest - Optional Features](https://docs.rs/reqwest/latest/reqwest/#optional-features)).

This choice may be provided by a feature in the crate keycloak itself.

**Comment by kilork** [comment]
I think this should be sufficient: #61. This would be released quite soon I think, I am planning another API bump, and this would be implemented there.

**Comment by ebakoba** [comment]
I support, just ran into this issue myself.

**Comment by kilork** [comment]
Fixed in #85
