### ISSUE TITLE
compatibility to keycloak 23 (subGroups, subGroupCount, groups/{id}/children API)

### ISSUE THREAD

**Issue by anthraxx** [kilork/keycloak#68]
Hi there, thank you a lot for this crate. It seems there are major changes in keycloak 23 that require to change f.e. `GroupRepresentation` as well as add new endpoints. Essentially running crate v21 against a 23 keycloak currently breaks in an unfixable way without this crate adapting new endpoints and struct changes:

One of the behaviors of 23 is, that the groups api does not return subGroups anymore, just a Count, and requires a new endpoint to fetch children of a group:
https://www.keycloak.org/docs/23.0.0/upgrading/#grouprepresentation-changes

The new API in question would be:
GET /admin/realms/{realm}/groups/{id}/children - Return a paginated list of subgroups that have a parent group corresponding to the group on the URL

I've noticed this repo contains an `update.sh` but I wasn't sure what kind of post-run tasks or checks need to be performed.

The following API docs are relevant (at least for the change I've noticed):
https://www.keycloak.org/docs-api/23.0.1/rest-api/index.html#GroupRepresentation
https://www.keycloak.org/docs-api/23.0.1/rest-api/index.html#_get_adminrealmsrealmgroups
https://www.keycloak.org/docs-api/23.0.1/rest-api/index.html#_get_adminrealmsrealmgroupsidchildren

**Comment by anthraxx** [comment]
@kilork It seems the documentation which is the source of truth has significantly changed. I made some tests refactoring in `examples/gen.rs` to account for that, I can share it in a WIP PR if that helps you. However, the documentation also made significant changes to the documented return types, that is the most problematic to adjust and figure out which values it should map to on rust side.

**Comment by kilork** [comment]
@anthraxx yes, you are very welcome! Sadly looks like with each release documentation is not really controlled for quality. But maybe it is not improving, we need to check :)

**Comment by anthraxx** [comment]
@kilork I've opened https://github.com/kilork/keycloak/pull/69 you should have commit/push access to that branch so we can work on this. Let's use the merge-request UI for discussing changes.

**Comment by fatslow** [comment]
> One of the behaviors of 23 is, that the groups api does not return subGroups anymore, just a Count, and requires a new endpoint to fetch children of a group: https://www.keycloak.org/docs/23.0.0/upgrading/#grouprepresentation-changes

I've had the same problem in typescript, and i noticed, that if you provide the additional query-parameters q=* and populateHierarchy=true, then the response contains again all subgroups, whereby the value for q doesnt matter, you can even set xyz as value. 

`{{base_url}}/admin/realms/{{realm}}/groups?q=*&populateHierarchy=true`

Even the keycloak-admin-client for Typescript, which is part of the Keycloak project, has not yet implemented this change.

**Comment by kilork** [comment]
I released based on `openapi.json` API, can you please check, if this issue still relevant?

**Comment by kilork** [comment]
Assuming it works, as no reply after 3 weeks.
