### ISSUE TITLE
Support service accounts and custom realm

### ISSUE THREAD

**Issue by wilsonhipolito** [kilork/keycloak#7]
Hello!
I'm new to Rust and I'm trying to consume the API using a service account and I realized the `acquire` method for `KeycloakAdminToken` only supports username/passwords (and it's also bound to the `master` realm). 

Is it possible to add more arguments in order to support a different `grant_type` (like "client_credentials") and select a diferent realm for the token retrieval?

**Comment by kilork** [comment]
Hi, can you maybe explain your use case?

Because of security keycloak itself actually recommends not to use `master` realm (https://www.keycloak.org/docs/latest/server_admin/index.html#the-master-realm).

I think as I implemented this I believed this is the only way to receive token to rule admin API, but after I received your question, I started to doubt :)

**Comment by wilsonhipolito** [comment]
Hello, thanks for the quick response!

I have an application which will create/update some clients in Keycloak, and I have 1 realm per environment (dev, qa, etc.).
So I'd like to have one service account for this application in each realm and then use these accounts to retrieve the admin API token.

Using this approach I won't need to create an user in the master realm to manage everything, making each environment independent.

I think we can add `realm` as an argument for the `acquire` function [here](https://github.com/kilork/keycloak/blob/master/src/rest/mod.rs#L40) and also add more arguments for `client_id`, `client_secret` and `grant_type`, but I have no idea in how to do that without breaking compatibility

**Comment by kilork** [comment]
I have some ideas about implementation, this should not be a big deal. Next `13.0.0` release would be a breaking change in any case. I am going to implement #5, after this definitely there would be no backward compatibility for most people using it. In any case it is not so many users, I almost have no feedback from this project.

**Comment by kilork** [comment]
I created the PR, can you check does it work for you @wilsonhipolito ?

**Comment by wilsonhipolito** [comment]
Yes! it's perfect @kilork 
Thank you very much!
Looking forward for the next relase :heart_eyes:

**Comment by kilork** [comment]
Thanks for feedback! It would probably be released this weekend.
