### ISSUE TITLE
Question: why doesnt the api return responses?

### ISSUE THREAD

**Issue by alexisgaziello** [kilork/keycloak#84]
I was wondering, why don't APIs return responses?

For example - the function in the example:

```
    pub async fn realm_users_post(
        &self,
        realm: &str,
        rep: UserRepresentation,
    ) -> Result<(), KeycloakError> {
        let builder = self
            .client
            .post(&format!("{}/admin/realms/{realm}/users", self.url))
            .json(&rep)
            .bearer_auth(self.token_supplier.get(&self.url).await?);
        let response = builder.send().await?;
        error_check(response).await?;
        Ok(())
    }
```

 Should ideally return `Ok(response)`
 
 In this specific case, for example, to retrieve the user ID that was just created.

**Comment by kilork** [comment]
I think most POST requests in REST APIs return 201 response code:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201

This means we return address of actual resource in `Location` header, or, if we return it in the body of POST request - it would mean it can be accessed by GET to the same address to which we send POST before. Which is obviously wrong.

I have not checked, if `keycloak` returns `Location` header, but there is no mention of it in documentation at least and this crate is based purely on documentation.
